#Emulicious settings file
#Mon Oct 13 23:22:17 BRT 2025
AudioSync=false
BankSwapAtPCBreakpointCondition=
BankSwapAtPCBreakpointEnabled=false
BankSwapAtPCBreakpointSuspend=true
CodeFontSize=13
CombineVideoViewers=true
DataExecutionBreakpointCondition=
DataExecutionBreakpointEnabled=false
DataExecutionBreakpointSuspend=true
DebuggerConsoleLogBreakpoints=true
DebuggerEventFiltersGameBoy=
DebuggerHideCpuUsageGraph=false
DebuggerHideToolbar=false
DebuggerMemorySelectedAddress=0
DebuggerMemorySelectedTab=VRAM
DebuggerMemoryTabVisibleRect=0,3799,583,190
DebuggerShowAddresses=true
DebuggerSouthPanelSelectedTab=0
DebuggerWestPanelSelectedTab=1
FontSize=13
GameBoyErrorBreakpointCondition0=
GameBoyErrorBreakpointCondition1=
GameBoyErrorBreakpointCondition10=
GameBoyErrorBreakpointCondition16=
GameBoyErrorBreakpointCondition17=
GameBoyErrorBreakpointCondition18=
GameBoyErrorBreakpointCondition19=
GameBoyErrorBreakpointCondition2=
GameBoyErrorBreakpointCondition20=
GameBoyErrorBreakpointCondition3=
GameBoyErrorBreakpointCondition4=
GameBoyErrorBreakpointCondition48=
GameBoyErrorBreakpointCondition5=
GameBoyErrorBreakpointCondition6=
GameBoyErrorBreakpointCondition7=
GameBoyErrorBreakpointCondition8=
GameBoyErrorBreakpointCondition9=
GameBoyErrorBreakpointEnabled0=false
GameBoyErrorBreakpointEnabled1=false
GameBoyErrorBreakpointEnabled10=true
GameBoyErrorBreakpointEnabled16=false
GameBoyErrorBreakpointEnabled17=false
GameBoyErrorBreakpointEnabled18=false
GameBoyErrorBreakpointEnabled19=false
GameBoyErrorBreakpointEnabled2=false
GameBoyErrorBreakpointEnabled20=false
GameBoyErrorBreakpointEnabled3=false
GameBoyErrorBreakpointEnabled4=false
GameBoyErrorBreakpointEnabled48=false
GameBoyErrorBreakpointEnabled5=false
GameBoyErrorBreakpointEnabled6=false
GameBoyErrorBreakpointEnabled7=false
GameBoyErrorBreakpointEnabled8=false
GameBoyErrorBreakpointEnabled9=false
GameBoyErrorBreakpointMessage0=
GameBoyErrorBreakpointMessage1=
GameBoyErrorBreakpointMessage10=
GameBoyErrorBreakpointMessage16=
GameBoyErrorBreakpointMessage17=
GameBoyErrorBreakpointMessage18=
GameBoyErrorBreakpointMessage19=
GameBoyErrorBreakpointMessage2=
GameBoyErrorBreakpointMessage20=
GameBoyErrorBreakpointMessage3=
GameBoyErrorBreakpointMessage4=
GameBoyErrorBreakpointMessage48=
GameBoyErrorBreakpointMessage5=
GameBoyErrorBreakpointMessage6=
GameBoyErrorBreakpointMessage7=
GameBoyErrorBreakpointMessage8=
GameBoyErrorBreakpointMessage9=
GameBoyErrorBreakpointSuspend0=true
GameBoyErrorBreakpointSuspend1=true
GameBoyErrorBreakpointSuspend10=true
GameBoyErrorBreakpointSuspend16=true
GameBoyErrorBreakpointSuspend17=true
GameBoyErrorBreakpointSuspend18=true
GameBoyErrorBreakpointSuspend19=true
GameBoyErrorBreakpointSuspend2=true
GameBoyErrorBreakpointSuspend20=true
GameBoyErrorBreakpointSuspend3=true
GameBoyErrorBreakpointSuspend4=true
GameBoyErrorBreakpointSuspend48=true
GameBoyErrorBreakpointSuspend5=true
GameBoyErrorBreakpointSuspend6=true
GameBoyErrorBreakpointSuspend7=true
GameBoyErrorBreakpointSuspend8=true
GameBoyErrorBreakpointSuspend9=true
InterruptBreakpointCondition=
InterruptBreakpointEnabled=false
InterruptBreakpointSuspend=true
OutlineWidth=266
Recent0=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent1=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent2=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent3=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent4=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent5=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent6=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent7=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent8=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
Recent9=/home/renan/Github/learning-retro-game-dev/GameBoy/04 - hollow knight/hollow-knight.gb
RomDir=/home/renan/GitHub/learning-retro-game-dev/GameBoy/unbricked
Scale=4.0
SouthPanelHeight=502
StackRomWriteBreakpointCondition=
StackRomWriteBreakpointEnabled=false
StackRomWriteBreakpointSuspend=true
StackSplitLocation=247
StackWidth=974
StretchToWindow=false
UninitializedMemoryBreakpointCondition=
UninitializedMemoryBreakpointEnabled=false
UninitializedMemoryBreakpointSuspend=true
Update=2
WindowBreakpointWindowHeight=888
WindowBreakpointWindowOpen=false
WindowBreakpointWindowWidth=569
WindowBreakpointWindowX=171
WindowBreakpointWindowY=8
WindowDebuggerHeight=840
WindowDebuggerOpen=false
WindowDebuggerWidth=1238
WindowDebuggerX=362
WindowDebuggerY=60
WindowEmuliciousHeight=629
WindowEmuliciousWidth=640
WindowEmuliciousX=610
WindowEmuliciousY=427
WindowPaletteViewerHeight=315
WindowPaletteViewerOpen=false
WindowPaletteViewerWidth=485
WindowPaletteViewerX=15
WindowPaletteViewerY=253
WindowSpriteViewerHeight=539
WindowSpriteViewerOpen=false
WindowSpriteViewerWidth=433
WindowSpriteViewerX=41
WindowSpriteViewerY=141
WindowTileViewerHeight=447
WindowTileViewerOpen=false
WindowTileViewerWidth=491
WindowTileViewerX=418
WindowTileViewerY=230
WindowTilemapViewerHeight=621
WindowTilemapViewerOpen=false
WindowTilemapViewerWidth=496
WindowTilemapViewerX=9
WindowTilemapViewerY=100
WindowVideoViewerHeight=802
WindowVideoViewerOpen=false
WindowVideoViewerWidth=995
WindowVideoViewerX=85
WindowVideoViewerY=72
